# Generated by Django 4.0.4 on 2022-06-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_order_number_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
